"Technische Universit\xC3\xA4t Berlin (TU Berlin) / Faculty of Planning Building Environment":
  additional_information:
    FAQs: Available on the university website
    contact_information: 'International Office: international@tu-berlin.de'
    testimonials: Student experiences available online
  address: "Stra\xC3\u0178e des 17. Juni 135, 10623 Berlin, Germany"
  application_and_admission:
    admission_statistics:
      acceptance_rate: Competitive; varies by year
      average_gpa: Not specified
      average_test_scores: Not applicable
    application_process:
      contact:
        email: studienberatung@tu-berlin.de
        phone: +49 30 314 29999
        web: https://www.tu.berlin/en/studying/application-and-enrollment/
      deadline: July 15, 2025
      open_days: April 10-11, 2025
      requirements:
        academic: Abitur or equivalent
        additional: German language proficiency (TestDaF, DSH)
  campus_and_student_life:
    campus:
      facilities:
      - Design Studios
      - GIS Labs
      - Computer Labs with BIM software
      - Libraries
      housing: University accommodations and private rentals available
      transportation: Excellent public transport connectivity
    student_live:
      culture: Dynamic and diverse community with a focus on sustainability and innovation
      extracurricular_activities:
      - Student planning societies
      - Environmental clubs
      - Workshops and seminars
      setting: Urban campus in central Berlin
      support_services: Academic advising, career services, counseling
  city: Berlin
  description: Focuses on sustainable urban development, environmental planning, and
    integrates technical skills with creative design processes.
  exchange_programs:
    partnering_schools:
    - application_process:
        deadline: Typically early 2025 for Winter Semester
        open_days: International Office events
        requirements: Good academic standing, language proficiency
      description: Exchange program focusing on urban planning and design.
      duration: One semester
      matching_score: '8'
      name: Delft University of Technology, Netherlands
      recommendation: Offers international perspective and exposure to innovative
        planning practices.
      structure: One semester abroad with collaborative projects
  field_of_study: Civil Engineering, Architecture, Urban Planning and Environmental
    Design
  industry_partnerships:
    partnering_companies:
    - application_process:
        deadline: Varies; check with the department
        open_days: Information sessions held periodically
        requirements: Application to the department; may require portfolio or project
          proposal.
      collaboratoin_type: Internships, project collaborations
      description: Collaboration on projects and internships in urban planning.
      matching_score: '8'
      name: Berlin Senate Department for Urban Development
      recommendation: Provides practical experience in real-world urban development
        projects.
      study_type: Optional internships during studies
      timeline_overview: Internships typically during semester breaks or integrated
        into studies.
    - application_process:
        deadline: Varies; early application recommended.
        open_days: Company presentations at the university.
        requirements: Application to BIM GmbH; may require portfolio.
      collaboration_type: Internships, workshops.
      description: Collaboration on projects and internships focused on BIM.
      matching_score: '8'
      name: BIM GmbH
      recommendation: Provides hands-on experience with BIM technologies.
      study_type: Integration of BIM projects into studies.
      timeline_overview: Opportunities throughout the program.
  internships_and_practical_experience:
    dual_programs:
      available: 'No'
      details: Dual vocational training not standard in this faculty
    internships:
      opportunities: Internships encouraged and sometimes integrated into the curriculum
      partnerships: Connections with government agencies and planning firms
    workshops:
      available: 'Yes'
      details: Workshops and practical projects are integral to the program
  matching_score: '8'
  post_graduation_outcomes:
    further_education: Master's programs in Urban Planning, Environmental Management,
      or related fields
    job_opportunities:
      description: Graduates work in urban planning offices, government agencies,
        and environmental consultancies.
      professions:
      - description_of_profession: Develops plans and programs for land use in urban
          areas.
        industries: Government agencies, planning firms, NGOs
        job_market_demand: Steady demand with growing emphasis on sustainable development
        profession_name: Urban Planner
        starting_salaries: "Approximately \xE2\u201A\xAC35,000 - \xE2\u201A\xAC45,000\
          \ per year"
        study_program: Bachelor of Science in Urban and Regional Planning
  recommendation: This faculty offers interdisciplinary programs that combine technical
    expertise with creative planning and environmental considerations, which aligns
    with Barbora's interest in combining creativity with practical skills. Potential
    professions include Urban Planner, Environmental Designer, or Landscape Architect.
  reputation_and_quality:
    accreditations: Programs accredited by relevant German accreditation agencies
    faculty_quality:
      individual_mentorship: Available through project-based courses and research
        opportunities
      notable_professors:
      - 'Prof. Dr.-Ing. Angela Million: Expert in urban design and planning'
      - 'Prof. Dr. Harald A. Mieg: Known for sustainable urban development'
      number_of_students: Approximately 2,000 students in the faculty
      student_teacher_ratio: Approximately 15:1
    ranking: TU Berlin is well-ranked globally, especially in engineering and environmental
      sciences.
  reputation_and_ranking:
    alumni_success: Graduates hold positions in government agencies and leading planning
      firms
    global_rankings:
      ARWU_Ranking: Ranked among top universities globally
      QS_Ranking: TU Berlin ranked within top 150 universities worldwide
      THE_Ranking: Similar global ranking
    national_rankings: Highly regarded in Germany for planning and environmental studies
  study_programs:
    description: Offers Bachelor's and Master's programs in Urban Planning, Landscape
      Architecture, and Environmental Planning.
    programs:
    - curriculum:
        core_courses:
        - Urban Design
        - Planning Law
        electives:
        - Sustainable Development
        - GIS Applications
      description: Provides foundational knowledge in urban planning, design, and
        sustainable development.
      duration: 3 years
      entry_requirements: Abitur or equivalent; German proficiency
      language_of_instruction: German
      matching_score: '8'
      name: Bachelor of Science in Urban and Regional Planning
      recommendation: Offers a blend of creative and technical skills; suitable for
        Barbora's interests in hands-on, practical learning.
      specialization: Urban Planning and Development
      timeline_overview: 3-year program with project work and practical exercises.
      type: Bachelor
      url: https://www.tu.berlin/en/studying/study-programs/all-programs-offered/study-course/urban-and-regional-planning-b-sc/
    - curriculum:
        core_courses:
        - Plant Knowledge
        - Landscape Design
        electives:
        - Ecological Planning
        - Landscape Ecology
      description: Focuses on designing outdoor spaces, integrating environmental
        and aesthetic considerations.
      duration: 3 years
      entry_requirements: Abitur or equivalent; German proficiency
      language_of_instruction: German
      matching_score: '7'
      name: Bachelor of Science in Landscape Architecture
      recommendation: Good for combining creativity with environmental awareness,
        but may be less technical.
      specialization: Landscape Design and Planning
      timeline_overview: 3-year program with design studios and fieldwork.
      type: Bachelor
      url: https://www.tu.berlin/en/studying/study-programs/all-programs-offered/study-course/landscape-architecture-b-sc/
    - curriculum:
        core_courses:
        - Structural Analysis
        - Construction Materials
        electives:
        - Building Information Modeling
        - Sustainable Construction
      description: Combines engineering principles with modern construction technologies.
      duration: 3 years.
      entry_requirements: Abitur or equivalent; proficiency in German.
      language_of_instruction: German
      matching_score: '7'
      name: Bachelor of Science in Civil Engineering
      recommendation: Aligns with practical skills and creative interests.
      specialization: Civil Engineering with BIM integration
      timeline_overview: 3-year program with practical projects.
      type: Bachelor
      url: https://www.tu.berlin/en/studying/study-programs/all-programs-offered/study-course/civil-engineering-b-sc/
  timeline_overview: Bachelor programs typically span 6 semesters (3 years), with
    options for master's studies.
  tuition_and_financials:
    additional_costs:
      living: "Approximately \xE2\u201A\xAC800-\xE2\u201A\xAC1,000 per month"
      materials: "Estimated \xE2\u201A\xAC300-\xE2\u201A\xAC500 per year for supplies"
      transportation: Public transport pass included in semester fee
    scholarships_and_aid:
      available_scholarships:
      - application_deadline: Usually in early summer
        description: Merit-based scholarship
        eligibility: High academic achievement
        name: Deutschlandstipendium
      financial_aid_options: "BAf\xC3\xB6G for eligible students, student loans"
    tuition_fees:
      domestic: "No tuition fees; semester fee around \xE2\u201A\xAC307"
      international: Same as domestic; no tuition fees
  type: "Technische Universit\xC3\xA4t"
  web: https://www.planen-bauen-umwelt.tu-berlin.de/
